From: Chris Warburton <chriswarbo@googlemail.com>
To: TOADDRESS
Subject: Join us to celebrate our wedding!
Date: Thu, 07 May 2021 22:00:43 +0100
MIME-Version: 1.0
Content-Type: multipart/related; boundary="RelatedBoundaryString"

--RelatedBoundaryString
Content-Type: multipart/alternative; boundary="AlternativeBoundaryString"

--AlternativeBoundaryString
Content-Type: text/plain;charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Dear TONAME,

Joanne Payne & Chris Warburton request the pleasure of your company at
their wedding celebration.

SATURDAY 11th DECEMBER 2021

SHUSTOKE BARNS, B46 2BL

Given the ever-changing situation with COVID-19 we have created a
wedding website which will help keep our guests in the loop should
circumstances change.

You can RSVP, view the venue location, nearby accommodation and more.

We can't wait to celebrate with you!

RSVP at http://chrisandjowedding.info

--AlternativeBoundaryString
Content-Type: text/html;charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
  </head>
  <body>
    <table border=3D"0" style=3D"border-color: red;" cellspacing=3D"0" cellpadding=3D"0">
      <tr height=3D"48">
        <td rowspan=3D"2" height=3D"164">
          <img class=3D"T96P6A"
               src=3D=22cid:s.png=40chrisandjowedding.info=22
               draggable=3D"false"
               width=3D"228"
               height=3D"164"
               style=3D"object-fit: fill;" />
        </td>
        <td colspan=3D"2" height=3D"66" align=3D"left" valign=3D"top">
          <p style=3D"font-size: 28px; color: rgb(194, 58, 71); line-heig=
ht: 1.1em; letter-spacing: 0.025em;" class=3D"uY5lhA Xc6mIg _-2C0Rg">
            <span style=3D"color: rgb(194, 58, 71);" class=3D"_8wBGSw">Jo=
in us to celebrate our wedding!
            </span>
          </p>
        </td>
      </tr>
      <tr>
        <td width=3D"68" height=3D"96"><!-- empty spacer --></td>
        <td rowspan=3D"2" valign=3D"top">
          <div class=3D"V86iwg NPoRiQ"
               style=3D"transform: translate(0.239511px, 0.958045px); font-=
size: 19.1609px; line-height: 1.1em; letter-spacing: 0.025em; "
               lang=3D"en-GB">
            <p class=3D"uY5lhA">
              Dear TONAME,
            </p>
            <p class=3D"uY5lhA">
              Joanne Payne &amp; Chris Warburton request the pleasure of
              your company at their wedding celebration.
            </p>
            <p class=3D"uY5lhA">
              SATURDAY 11th DECEMBER 2021
            </p>
            <p class=3D"uY5lhA">SHUSTOKE BARNS, B46 2BL</p>
            <p class=3D"uY5lhA">
              Given the ever-changing situation with COVID-19 we have
              created a <a href=3D"http://chrisandjowedding.info">
                wedding website
              </a>
              which will help keep our guests in the loop should
              circumstances change
            </p>
            <p class=3D"uY5lhA">
              You can RSVP, view the venue location, nearby accommodation
              and more.
            </p>
            <p class=3D"uY5lhA">
              We can't wait to celebrate with you!
            </p>
            <p class=3D"uY5lhA">
              <a href=3D"http://chrisandjowedding.info">
                <button style=3D"background-color: rgb(163, 3, 3); color: r=
gb(255, 255, 255); min-height: 40px; border-style: solid; border-width: 1px=
; cursor: pointer; font-size: 12.8px; font-weight: 400; padding: 0 16px; di=
splay: inline-block;">
                  CLICK HERE TO RSVP
                </button>
              </a>
            </p>
            <p class=3D"uY5lhA"><br></p>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan=3D"2">
          <img class=3D"T96P6A"
               width=3D"296"
               height=3D"296"
               src=3D=22cid:w.png=40chrisandjowedding.info=22
               draggable=3D"false"
               style=3D"object-fit: fill;" />
        </td>
      </tr>
    </table>
  </body>
</html>

--AlternativeBoundaryString--

--RelatedBoundaryString
Content-Type: image/png;name="w.png"
Content-Transfer-Encoding: base64
Content-Disposition: inline;filename="w.png"
Content-ID: <w.png@chrisandjowedding.info>

IMAGEDATA1

--RelatedBoundaryString
Content-Type: image/png;name="s.png"
Content-Transfer-Encoding: base64
Content-Disposition: inline;filename="s.png"
Content-ID: <s.png@chrisandjowedding.info>

IMAGEDATA2

--RelatedBoundaryString--
